import { AnimationType } from "../stores/animationPopupStore";

export const HOLIDAY_ASSETS: Partial<Record<AnimationType, string>> = {
  diwali: "https://guidelensapp-dc28c30e.web.app/lottie/diwali.json",
  republic_day: "https://guidelensapp-dc28c30e.web.app/lottie/republic_day.json",
  independence_day: "https://guidelensapp-dc28c30e.web.app/lottie/independence_day.json",
  christmas_eve: "https://guidelensapp-dc28c30e.web.app/lottie/christmas_eve.json",
  christmas: "https://guidelensapp-dc28c30e.web.app/lottie/christmas.json",
  bakrid: "https://guidelensapp-dc28c30e.web.app/lottie/bakrid.json",
  bhai_duj: "https://guidelensapp-dc28c30e.web.app/lottie/bhai_duj.json",
  buddha_purnima: "https://guidelensapp-dc28c30e.web.app/lottie/buddha_purnima.json",
  dussehra: "https://guidelensapp-dc28c30e.web.app/lottie/dussehra.json",
  eid: "https://guidelensapp-dc28c30e.web.app/lottie/eid_al_fitr.json",
  good_friday: "https://guidelensapp-dc28c30e.web.app/lottie/good_friday.json",
  holi: "https://guidelensapp-dc28c30e.web.app/lottie/holi.json",
  makar_sankranti: "https://guidelensapp-dc28c30e.web.app/lottie/makar_sankranti.json",
  new_year: "https://guidelensapp-dc28c30e.web.app/lottie/new_year.json",
  pongal: "https://guidelensapp-dc28c30e.web.app/lottie/pongal.json",
  ram_navami: "https://guidelensapp-dc28c30e.web.app/lottie/ram_navami.json",
  maha_shivaratri: "https://guidelensapp-dc28c30e.web.app/lottie/maha_shivaratri.json",
  mahavir_jayanti: "https://guidelensapp-dc28c30e.web.app/lottie/mahavir_jayanti.json",
  milad_un_nabi: "https://guidelensapp-dc28c30e.web.app/lottie/milad_un_nabi.json",
  rakshabandhan: "https://guidelensapp-dc28c30e.web.app/lottie/rakshabandhan.json",
  gandhi_jayanti: "https://guidelensapp-dc28c30e.web.app/lottie/gandhi_jayanti.json",
  guru_nanak: "https://guidelensapp-dc28c30e.web.app/lottie/guru_nanak_jayanti.json",
  janmashtami: "https://guidelensapp-dc28c30e.web.app/lottie/janmashtami.json",
  muharram: "https://guidelensapp-dc28c30e.web.app/lottie/muharram.json",
  birthday: "https://guidelensapp-dc28c30e.web.app/lottie/happy-birthday.json",
  exam: "https://guidelensapp-dc28c30e.web.app/lottie/exam.json",
  practical: "https://guidelensapp-dc28c30e.web.app/lottie/lab_exam.json"
};
